### ISSUE TITLE
Repository name change request

### ISSUE THREAD

**Issue by amircherif-ac** [karyennevu/GENERALs-soen341project2022#1]
Hi !

In the project description provided by the professor, she is asking us that the repository name is in this format:
<team_name-soen341project2022>
I tried to change it but I don't have the permissions to do it. According to GitHub Doc only the owner is authorized to do it.

Can you please change the name of the repository to:  group_c-soen341project2022

Thank you

**Comment by karyennevu** [comment]
Oh sorry I just saw your request to change the team name to group c. Would you prefer group C or are you okay with the name I just changed it into?

**Comment by amircherif-ac** [comment]
Yes ! That's perfect ! 
Generals ! Love that !
Thank you

**Comment by karyennevu** [comment]
Thank YOU!
