### ISSUE TITLE
Documenting the minutes for our meeting under wiki.

### ISSUE THREAD

**Issue by beshoikhair** [karyennevu/GENERALs-soen341project2022#2]
Hi Nelly and Amir, 

For Nelly, Since you are responsible about the meeting minutes, I am just reminding you that you should write them under **the wiki tab** in our repository  as it is mentioned in the excel file **Not in the meeting file under the Code tab** . Thank you so much, Nelly.

For Amir, in the folder "Meetings-Minutes", try to leave a note there shows that our meetings' minutes are under the wiki tab, Thank you Amir so much.

**Comment by nellyb4** [comment]
I have written our minutes under the wiki tab, for issue #2.
