### ISSUE TITLE
As a seller, I want to be able to find my customer's email address, because I want to be able to contact them to discuss something about their order.

### ISSUE THREAD

**Issue by karyennevu** [karyennevu/GENERALs-soen341project2022#27]
User story for core feature #26 on Managing your profile,

**Comment by karyennevu** [comment]
- From the account dashboard, the seller can click on "Orders" button.

- Then, they can scroll through their customers' orders and user information of these people.

- The seller can then find the customer they want to contact and their corresponding email address.

**Comment by karyennevu** [comment]
@beshoikhair Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you.

**Comment by beshoikhair** [comment]
A potential risk for this feature: 
If the customer's email is inactive and the customer is not using the email on his account , there is a risk that a miscommunication can happen between the seller and the customer, this can lead to a delay in the shipment of the order. So I suggest we should make sure that the customer's account has more than 2 methods of contact such as email and phone number.

**Comment by DragonGawain** [comment]
Acceptance tests have been verified.
Risks have been verified. 
Marking user story as closed.
