### ISSUE TITLE
As an admin, I want to be able to change my password every now and then, because I want to make sure that the website security will not be compromised.

### ISSUE THREAD

**Issue by karyennevu** [karyennevu/GENERALs-soen341project2022#28]
User story for core feature #26  on Managing your profile.

**Comment by karyennevu** [comment]
- The user first signs in as an admin.

- Then, they can click on the "Manage Users" page.

- Then, the admin can click on the edit button next to the admin user.

- Finally, I need to enter my current password, my new password and a repeat of my new password to confirm.

**Comment by karyennevu** [comment]
@beshoikhair Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you.

**Comment by beshoikhair** [comment]
A potential risk for this feature:
if an admin changes his/her password many times in a short time, there is a risk that the admin will forget his/her recent password which leads to not accessing his/her account. So, the website should send a link to the admin's email to reset his/her password.

**Comment by DragonGawain** [comment]
Acceptance tests have been verified.
Risks have been verified. 
Marking user story as closed.
