### ISSUE TITLE
As an admin, I want to be able to remove users, because the user requested to close/delete their account.

### ISSUE THREAD

**Issue by karyennevu** [karyennevu/GENERALs-soen341project2022#29]
User story for core feature https://github.com/karyennevu/GENERALs-soen341project2022/issues/26 on Managing your profile.

**Comment by karyennevu** [comment]
- The user first signs in as an admin.

- Then, they can click on the "users" button.

- Finally, through the users list, they can search for the specified user and click on the delete button to remove that account.

**Comment by karyennevu** [comment]
@beshoikhair Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you.

**Comment by DragonGawain** [comment]
Acceptance tests have been verified. 
Marking user story as closed.
