### ISSUE TITLE
Plans for Sprint 2

### ISSUE THREAD

**Issue by beshoikhair** [karyennevu/GENERALs-soen341project2022#3]
For Sprint 2
1. We need at least to make 3 meetings for this sprint.
2. Create Task Break Down for this sprint including deadlines for each task.
3. Include new User stories for the new features of the app with some details.
4. Make sure that all the team members have Integrated the Git-Hub repository to their IDEs.
5. Prepare Plans for Sprint 3.

**Comment by amircherif-ac** [comment]
As mentioned in #4, 
6. We will discuss the detail of the implementation of the new user category in our next Scrum. 
7. We will review it with product owners(TA and instructor) to ensure that it does not compromise the critical business needs and to measure its business added value.
