### ISSUE TITLE
As a seller, I want to be able to change the address from which I ship out my customers' packages, because I moved to a new warehouse.

### ISSUE THREAD

**Issue by karyennevu** [karyennevu/GENERALs-soen341project2022#30]
User story for core feature https://github.com/karyennevu/GENERALs-soen341project2022/issues/26 on Managing your profile.

**Comment by karyennevu** [comment]
- From the "My Account"/"Dashboard" page, the seller can click on "Addresses".

- The user can then click on the "Edit" button next to the ship from address.

- The seller can then choose their Country and their Province/Territory from a list.

- The seller can also erase the previous Address, City, Postal Code and even Phone Number and enter their new information.

- Finally, the customer can click on Save Changes to complete the edit.

**Comment by karyennevu** [comment]
@beshoikhair Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you.

**Comment by beshoikhair** [comment]
A potential risk for this feature:
If the seller forgot to update his new warehouse address, there is a risk that the shipping fees and estimated delivery date will be completely different from the actual ones which can lead to misleading and incorrect information given to the customer. So I suggest that the website should pop up a screen once per month asking the seller if he changed his address or not?

**Comment by DragonGawain** [comment]
Acceptance tests have been verified.
Risks have been verified. 
Marking user story as closed.
