### ISSUE TITLE
As a Customer, I want to determine the quantity of the product that I will purchase, because I want all of them to be shipped in one order. 

### ISSUE THREAD

**Issue by beshoikhair** [karyennevu/GENERALs-soen341project2022#31]
User Story for Core Feature #23 on Adding Items to shopping carts.

**Comment by beshoikhair** [comment]
@karyennevu Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you.

**Comment by DragonGawain** [comment]
Acceptance tests have been verified. 
Marking user story as closed.

**Comment by karyennevu** [comment]
If the customer is unable to edit the quantity of the item they want to order, then there is a risk that the customer will have to make several orders of the same product and so the customer may opt to give up on ordering the product to avoid the hassle of putting several orders and the sales may go down. We suggest that we implement an interface that lets customers change the quantity of a product that they want to order to their liking.
