### ISSUE TITLE
As a Customer, I want to remove individual products from my cart directly, because I don't want to cancel the whole order just to remove one item from my cart.

### ISSUE THREAD

**Issue by beshoikhair** [karyennevu/GENERALs-soen341project2022#32]
User Story for Core Feature #23 on Adding Items to shopping carts.

**Comment by beshoikhair** [comment]
@karyennevu Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you.

**Comment by karyennevu** [comment]
If the software does not let customers edit individual products out of their cart containing many items, then there is a risk that the customer will have to cancel their whole cart and re-add all the items one by one again and so this could lead to the customer forgetting to re-add one or a few items back into their cart which would lead to a lost in a potential sale. We suggest implementing the editing feature before dispatching the website to ensure that we give the customers the benefit of changing the items in their cart without having to start over each time.

**Comment by DragonGawain** [comment]
Acceptance tests have been verified.
Risks have been verified. 
Marking user story as closed.
