### ISSUE TITLE
As an admin, I want an automatic email to be sent to the customer and the seller after each purchase, because I want this email as a confirmation of the purchase success.

### ISSUE THREAD

**Issue by beshoikhair** [karyennevu/GENERALs-soen341project2022#47]
User Story for Core Feature #23 on Adding Items to shopping carts.

**Comment by beshoikhair** [comment]
@karyennevu Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you

**Comment by karyennevu** [comment]
If the automatic confirmation email system is not implemented or does not function, then there is a risk that the customer and the seller will not receive a confirmation of a successful purchase and so there could be confusion and frustration from the customer's side as they don't know what if their payment/order went through as well as a delay in the shipment from the seller's side as they may not immediately notice that they have a new order to ship out. We suggest to implement the automatic confirmation email system before having customers  be able to place orders and to ensure that that it is always functioning properly to avoid such impacts.

**Comment by DragonGawain** [comment]
Acceptance tests have been verified.
Risks have been verified. 
Marking user story as closed.
