### ISSUE TITLE
Plan for Sprint 4

### ISSUE THREAD

**Issue by beshoikhair** [karyennevu/GENERALs-soen341project2022#51]
1. Finish all of the remaining user stories within every core feature.
2. Finish coding the remaining extra features for the website.
3. Test the code many times to take care with all of the possibilities of errors and the exceptions that could occur.
4. Start cleaning the code for final submission.
5. Ask regular users (not the members of the team) to try the website and take feedback.
6. Divide the feedback into "for sprint 4" and "for future" based on the complexity of the things to be changed.
7. Change the things "for sprint4" in our website
8. Do final test for our website.
9. Start working on the presentation of the project.

**Comment by DragonGawain** [comment]
Plan accepted
