### ISSUE TITLE
As a user, I want to be able to zoom in on pictures, so I can see their quality better

### ISSUE THREAD

**Issue by DragonGawain** [karyennevu/GENERALs-soen341project2022#58]
Story points: 5

Related to #61

**Comment by DragonGawain** [comment]
From the product page, 
the user moves the mouse over the product image
the image should dynamically zooms in slightly

Succes case: 
Image zooms in


Failure case:
Image remains static

**Comment by DragonGawain** [comment]
Risks:
Modifying an image dynamically can cause issues with the image if done improperly. 
It can lead to issues such as the image disappearing or becoming otherwise very difficult to look at. 
In addition, after moving the mouse off of the image, the altercations may remain. 

However, refreshing the page should restore the image to its original state.

**Comment by DragonGawain** [comment]
@karyennevu please verify acceptance tests and risks and close issue.

**Comment by karyennevu** [comment]
The risks and acceptance tests are verified.
