### ISSUE TITLE
As a user, seller, and admin, I want to see if a product is out of stock

### ISSUE THREAD

**Issue by DragonGawain** [karyennevu/GENERALs-soen341project2022#59]
Story points: 3

Related to #61

**Comment by DragonGawain** [comment]
On any store or product page
When looking at an item
I want to see if an product is out of stock

Success case: 
item show out of stock


Failure case:
item does not show out of stock

**Comment by DragonGawain** [comment]
Risks: 
An item may show out of stock even if it is not

**Comment by DragonGawain** [comment]
@karyennevu Please verify acceptance tests and risks, and close user story.

**Comment by karyennevu** [comment]
The risks and acceptance tests are verified.
