### ISSUE TITLE
As a customer, I want to be able to find groupings of items easily, because I don't want to search the entire catalogue of items on the website for one thing.

### ISSUE THREAD

**Issue by nellyb4** [karyennevu/GENERALs-soen341project2022#6]
As a user, I want to be able to go to find the items that I want easily because I don't want to have to search through the entire catalogue of items on the website.

**Comment by nellyb4** [comment]
As a user, I want to be able to have access to my profile because I would like to be able to change my email and username.

**Comment by maxxfreund** [comment]
This is for the "Browsing for Items" feature

**Comment by maxxfreund** [comment]
- The user may navigate different sections or "aisles" of the site using the navigation bar
- Different buttons will exist on the navigation bar, that when clicked will bring the user to a page about the items in the specified section
- This serves as an alternative to using the search bar to search for items
