### ISSUE TITLE
As a user, seller, and admin, I want the website to remember my username and password so I can access my account with ease

### ISSUE THREAD

**Issue by DragonGawain** [karyennevu/GENERALs-soen341project2022#60]
When logging into my account
I was to be able to click a checkbox that says 'Remember me'
If I check this checkbox,
The next time I attempt to log in from the same computer, 
I want to be logged in automatically. 

Story points: 3

Related to #61

**Comment by karyennevu** [comment]
Scenario: Remember credentials. (Success case)

“Given that I am a customer of the website
And I want to access my account with ease,
When I click the user icon,
And I enter my username and password,
And I click on the "Remember Me" button,
And I click on "Log In",
Then, next time, I should be able to only click on "Log In" without needing to re-enter my credentials as the website saved them."


Scenario: Remember credentials. (Failure case)

“Given that I am a customer of the website
And I want to access my account with ease,
When I click the user icon,
And I enter the wrong username and/or password,
And I click on the "Remember Me" button,
And I click on "Log In",
Then, it won't remember the "wrong" credentials."

**Comment by DragonGawain** [comment]
Acceptance tests verified. 
Closing story.
