### ISSUE TITLE
As a customer, I want to be able to change my username, email and password, because I'm concerned about my previous information being compromised

### ISSUE THREAD

**Issue by nellyb4** [karyennevu/GENERALs-soen341project2022#7]
As a user, I want to be able to have access to my profile because I would like to be able to change my email and username.

**Comment by maxxfreund** [comment]
- After logging in, the user may navigate to their profile page
- They can click the "Account details" button to reach a page displaying their information
- They may alter their display name, email address and password for the account
- Clicking "Save changes" will complete these edits

**Comment by karyennevu** [comment]
This is for the "Managing your profile" feature #26 .
